Task 1
VladislawL/phoneshop pull request #1
Opened 2020-05-22 12:34 UTC by VladislawL

2020-05-22 13:18 UTC, AndreikaInactive requested changes

2020-05-22 13:18 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        return Optional.of(jdbcTemplate.queryForObject("select * from phones where phones.id = ?", new PhoneRowMapper(), key));
квери в константы, маппер можно сделать бином для реюза
подумай что будет если ничего не найдётся

2020-05-22 13:18 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        return jdbcTemplate.query("select * from phones offset " + offset + " limit " + limit, new PhoneRowMapper());
то же

2020-05-22 13:18 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        jdbcTemplate.update(UPDATE_QUERY, phone.getBrand(), phone.getModel(), phone.getPrice(), phone.getDisplaySizeInches(),
сделай через map sql source или что то такое, будет читабельнее

2020-05-22 13:18 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +            jdbcTemplate.update("insert into phone2color (phoneId, colorId) values (?, ?)", phone.getId(), color.getId());
лучше в отдельный метод

2020-05-22 13:18 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        SimpleJdbcInsert simpleJdbcInsert = new SimpleJdbcInsert(jdbcTemplate.getDataSource())
можно обхявить заранее

2020-05-22 13:18 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +                    " join colors on colorId = colors.id where phoneId = " + phone.getId(), new BeanPropertyRowMapper(Color.class));
можно заинжектить другой маппер

2020-05-22 13:18 UTC, AndreikaInactive commented on core/src/test/java/com/es/core/model/phone/JdbcPhoneDaoTest.java
> +@RunWith(SpringJUnit4ClassRunner.class)
сделай какой нибудь абстрактный класс для интегрейшен тестов, подумай что сделать чтобы данные не оставались в базе после тестов

2020-05-22 13:18 UTC, AndreikaInactive commented on core/src/test/java/com/es/core/model/phone/JdbcPhoneDaoTest.java
> +        assertNotNull(phones);
посмотри либу assertj, довольно простая и много удобный ассертов на все случаи

2020-05-22 13:18 UTC, AndreikaInactive commented on core/src/test/java/com/es/core/model/phone/JdbcPhoneDaoTest.java
> +    public void testGet() {
обычно в названии теста пишут кейс - shouldUpdateExistingPhone, shouldFailIfConstraintViolated итд

2020-05-25 09:09 UTC, AndreikaInactive requested changes

2020-05-25 09:09 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +    private final String INSERT_QUERY = "insert into phones (id, brand, model, price, displaySizeInches, weightGr, " +
INSERT_PHONE_QUERY

2020-05-25 09:09 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        } catch (Exception e) {
это bad practice, лови специфичный эксепшен под свои нужды

2020-05-25 09:09 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        namedParameterJdbcTemplate.update(DELETE_QUERY, idParameter);
тоже непонятно, что за квери - имя константы должно говорить о её назначении

2020-05-25 09:09 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/PhoneRowMapper.java
> +                " join colors on colorId = colors.id where phoneId = " + phone.getId(), new BeanPropertyRowMapper(Color.class));
вынести в бин

2020-05-25 09:09 UTC, AndreikaInactive commented on core/src/test/java/com/es/core/model/phone/AbstractDataBaseIT.java
> +@PropertySource(value = "classpath:config/application.properties")
то же что и у брата по тестам, и что за IT? просто AbstractIntegrationTest

2020-05-25 09:09 UTC, AndreikaInactive commented on core/src/test/java/com/es/core/model/phone/JdbcPhoneDaoIT.java
> +        assertNotNull(phones);
ассерты так и остались juntitoвские

2020-05-25 14:43 UTC, VladislawL commented on core/src/main/java/com/es/core/model/phone/PhoneRowMapper.java
> +                " join colors on colorId = colors.id where phoneId = " + phone.getId(), new BeanPropertyRowMapper(Color.class));
А что именно вынести в бин? BeanPropertyRowMapper? Просто ему нужен класс для его создания, или это можно типа заранее подготовить.

2020-05-25 14:44 UTC, VladislawL commented on core/src/main/java/com/es/core/model/phone/PhoneRowMapper.java
> +                " join colors on colorId = colors.id where phoneId = " + phone.getId(), new BeanPropertyRowMapper(Color.class));
Просто, в зависимости от того что нам нужно замапить будут разные BeanPropertyRowMapper

2020-05-25 14:54 UTC, VladislawL commented on core/src/main/java/com/es/core/model/phone/PhoneRowMapper.java
> +                " join colors on colorId = colors.id where phoneId = " + phone.getId(), new BeanPropertyRowMapper(Color.class));
Всё, вроде понял

2020-05-26 09:22 UTC, AndreikaInactive requested changes

2020-05-26 09:22 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/PhoneDao.java
> +@Transactional
зачем на интерфейс?

2020-05-26 09:22 UTC, AndreikaInactive commented
резолвай плз те дискуссии, которые пофиксил

2020-05-26 13:16 UTC, VladislawL commented on core/src/main/java/com/es/core/model/phone/PhoneDao.java
> +@Transactional
Чтобы классы, которые будут его имплементить тоже были transactional. Или нужно конкретные реализации делать transactional? И надо ли она нам?

2020-05-26 16:05 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/PhoneDao.java
> +@Transactional
интерфейс не должен нести деталей имплементации, плюс могут возникнуть проблемы с прокси
ты ведь проверял что она работает?
и вообще, как правило транзакцию надо начинать выше уровнем, но это уже потом будете делать

2020-05-26 18:40 UTC, AndreikaInactive approved these changes

2020-05-26 18:40 UTC, merged

2020-05-26 18:40 UTC, AndreikaInactive commented
коммиты старайся называть информативней