Task 2 implement productlist page
VladislawL/phoneshop pull request #2
Opened 2020-06-01 17:02 UTC by VladislawL

2020-06-02 21:26 UTC, AndreikaInactive requested changes

2020-06-02 21:26 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/CartItem.java
> +    private long phoneId;
не будет проблем с 0 по дефолту?

2020-06-02 21:26 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        if (cart.getCartItems().stream().anyMatch(cartItem -> cartItem.getPhoneId().equals(phoneId))) {
почему не использовать findCartItem и здесь?

2020-06-02 21:26 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +    private BigDecimal calculateSubTotalPrice() {
вынеси логику подсчёта в отдельный сервис

2020-06-02 21:26 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +            subTotalPrice = subTotalPrice.add(phone.getPrice().multiply(BigDecimal.valueOf(cartItem.getQuantity())));
можно сделать через стримы

2020-06-02 21:26 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/dao/JdbcPhoneDao.java
> +    private final String FIND_ALL_PHONES_WITH_OFFSET_AND_LIMIT_QUERY = "select * from phones offset :offset limit :limit";
static

2020-06-02 21:26 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/dao/JdbcStockDao.java
> +        Map<String, Object> parameters = new HashMap<>();
логика подсчёта стока может быть значительно сложнее - лучше возвращай сток, а итоговое колво считай в сервисе

2020-06-02 21:26 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/SortField.java
> +public enum SortField {
возможные сортировки лучше держать в конфиге, т.к потенциально будут изменяться

2020-06-02 21:26 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/services/DefaultPhoneService.java
> +        int limit = 10;
а лимит должен быть захардкодан или передаваться парамом? как минимум в конфиг вынести

2020-06-02 21:26 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/services/DefaultPhoneService.java
> +        return phoneDao.countPhonesWhereBrandAndModelLikeSearchQuery(searchQuery) / 10;
и здесь непонятно

2020-06-02 21:26 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/services/DefaultPhoneService.java
> +        return phoneDao.get(id).get();
а если не будет в базе?

2020-06-02 21:26 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/validators/StockValidator.java
> +public class StockValidator implements ConstraintValidator<QuantityConstraint, Object> {
во первых непонятно почему относится именно к QuantityConstraint , во вторых - выглядит как типичный оверинжиниринг, понятней явно проверять перед изменением айтема

2020-06-02 21:26 UTC, AndreikaInactive commented on pom.xml
> +      <dependency>
а почему в помы добавляются одни и те же депенденси?

2020-06-02 21:26 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/advicer/AjaxExceptionHandler.java
> +        Map<String, Object> errorMessage = new HashMap<>();
сделай отдельный бин под эрроры

2020-06-02 21:26 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
> +            miniCart.put("subTotalPrice", cart.getSubTotalPrice().toString());
сделай отдельный бин под миникарт, добавь для неё отдельный метод, не надо форматировать через toString

2020-06-02 21:26 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
> +            throw new CartItemValidationException(errors.getAllErrors().get(0).getDefaultMessage());
а остальные зачем терять? передавай весь errors в эксепшен

2020-06-02 21:26 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/ProductListPageController.java
> +        model.addAttribute("phones", phoneService.getPhonePage(page, query, sortField, sortOrder));
если возвращает пейдж - по идее там сразу же должна быть и дата по пагинации

2020-06-02 21:26 UTC, AndreikaInactive commented on web/src/test/resources/context/applicationContext.xml
> +    <import resource="applicationContext-core.xml" />
а это всё зачем?

2020-06-02 21:26 UTC, AndreikaInactive commented on web/src/test/resources/config/application.properties
> +db.driver=org.h2.Driver
достаточно того что в коре

2020-06-02 21:26 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/dao/JdbcPhoneDao.java
> +        StringBuilder result = new StringBuilder("lower(brand) like '%" + searchQuery.toLowerCase() +
уязвимо для sql injection - парметры надо сетать только через ? :name

2020-06-02 21:26 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/dao/JdbcPhoneDao.java
> +                ") and stock > 0 and price > 0 order by " + sortField.getAttribute() + " " + sortOrder.name() + " offset " + offset + " limit " + limit, phoneRowMapper);
а если в полях будет null?

2020-06-02 21:26 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +            Map<Long, Long> cartItem = new HashMap<>();
попробуй выделить методы add/update phone и закинуть всю в них логику по валидации итд и переиспользовать в публичных addPhone и update

2020-06-02 22:45 UTC, VladislawL commented on web/src/test/resources/context/applicationContext.xml
> +    <import resource="applicationContext-core.xml" />
По другому не работало, тесты всё время падали с FileNotFoundException. Я думал так и должно быть. Тогда странно получается, попробую исправить чуть что отпишусь

2020-06-03 11:59 UTC, VladislawL commented on core/src/main/java/com/es/core/cart/CartItem.java
> +    private long phoneId;
По идее не должно быть. Этот объект будет создан только по информации, что пришла от клиента. А если будет какое-то несуществующее id или тот же 0, то телефон просто не будет найден.

2020-06-03 19:43 UTC, VladislawL commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +            Map<Long, Long> cartItem = new HashMap<>();
Я так понимаю будет без валидации спринга. Даже без @ Positive или @ NotNull

2020-06-04 18:17 UTC, VladislawL commented on core/src/main/java/com/es/core/dao/JdbcPhoneDao.java
> +                ") and stock > 0 and price > 0 order by " + sortField.getAttribute() + " " + sortOrder.name() + " offset " + offset + " limit " + limit, phoneRowMapper);
А что в таком случае стоит сделать, бросить ошибку или использовать какое-нибудь дефолтное значение?

2020-06-05 12:37 UTC, VladislawL commented on pom.xml
> +      <dependency>
Я не нашёл повторяющихся зависимостей

2020-06-05 12:40 UTC, VladislawL commented on web/src/main/java/com/es/phoneshop/web/controller/pages/ProductListPageController.java
> +        model.addAttribute("phones", phoneService.getPhonePage(page, query, sortField, sortOrder));
Вот тут я не понял. Нужно прям все найденные телефоны сетать в атрибут?

2020-06-05 12:42 UTC, VladislawL commented on web/src/test/resources/config/application.properties
> +db.driver=org.h2.Driver
Context в тестовой папке я удалил, а вот без этого файла падали тесты, где нужна была бд

2020-06-05 12:48 UTC, VladislawL commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +            Map<Long, Long> cartItem = new HashMap<>();
Positive и NotNull я оставил, но со стороны выглядит как-то не удобно, что при большом quantity я кидаю ошибку, а тут через errors чекаю. Может стоит всюду кидать ошибку, а в контроллере её хэндлить и упаковывать их в другую ошибку, которую в свою очередь перехватит ExceptionHandler.

2020-06-08 08:35 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/CartItem.java
> +    private long phoneId;
в данном случае мб и ок, но вообще не оч хорошо что мы не можем точно понять - новый это объект или уже сохранённый в бд

2020-06-08 08:55 UTC, AndreikaInactive requested changes

2020-06-08 08:55 UTC, AndreikaInactive commented on web/src/test/resources/config/application.properties
> +db.driver=org.h2.Driver
так а что здесь? в вебе и тестах не надо дупликатов, достаточно того что в коре лежит, ты же его подключаешь в тесты

2020-06-08 08:55 UTC, AndreikaInactive commented on web/src/test/resources/context/applicationContext.xml
> +    <import resource="applicationContext-core.xml" />
это надо удалить, ты скорей тесты не так запускаешь

2020-06-08 08:55 UTC, AndreikaInactive commented on web/src/main/webapp/WEB-INF/tags/sortLink.tag
> +<a href="<c:url value="/productList?query=${param.query}&sortField=${field}&sortOrder=${order}&page=1"/>" />
используя c url с парамами вместо мануальной конструкции

2020-06-08 08:55 UTC, AndreikaInactive commented on web/src/main/webapp/WEB-INF/tags/pagination.tag
> +    <c:when test="${currentPage - 6 < 0}">
что то вообще жесткий хардкод пошёл ) попробуй работать с параметрами pagination data объекта из контроллера - с текущей страницей, колвом результатов на страницу, общим колвом результатов

2020-06-08 08:55 UTC, AndreikaInactive commented on web/src/main/webapp/WEB-INF/tags/master.tag
> +                <span id="subtotal-price">$${cart.subTotalPrice}</span>
formatPrice тег какой используй из fn

2020-06-08 08:55 UTC, AndreikaInactive commented on web/src/main/webapp/WEB-INF/tags/pageLink.tag
> +    ${pageText}
текст обычно надёжнее рисовать через c:out - ескейпит всякие xss-сы

2020-06-08 08:55 UTC, AndreikaInactive commented on web/src/main/webapp/WEB-INF/pages/productList.jsp
> +      <th>
можно просто возвращать список полей для сортировки из контроллера и хэндлать в цикле

2020-06-08 08:55 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/ProductListPageController.java
> +        model.addAttribute("phones", phoneService.getPhonePage(page, query, sortField, sortOrder));
сделай pagination data бин и туда сетай телефоны, плюс pagesCount, сортировку, страницу итд

2020-06-08 08:55 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/converter/StringToSortOrder.java
> +            return Enum.valueOf(SortOrder.class, sortOrder);
думаю спринг и сам умеет это конвертить в контроллере, чекни

2020-06-08 08:55 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/converter/StringToSortFieldConverter.java
> +            return Enum.valueOf(SortField.class, sortField);
см ниже

2020-06-08 08:55 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +            subTotalPrice = subTotalPrice.add(phone.getPrice().multiply(BigDecimal.valueOf(cartItem.getQuantity())));
а почему зарезолвал?

2020-06-08 08:55 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +    private BigDecimal calculateSubTotalPrice() {
?

2020-06-08 08:55 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +            Map<Long, Long> cartItem = new HashMap<>();
аннотации хэндлать выше, на уровне валидатора формы - там да, показывать на ui, а здесь разве что ассертнуть что qty валидный инт

2020-06-08 08:57 UTC, VladislawL commented on web/src/test/resources/config/application.properties
> +db.driver=org.h2.Driver
Ну да я подключаю, но тесты почему то падают с FileNotFoundException и указывается файл с test-data.sql, хота например тот же schema.sql загружается. Тогда попробую что нибудь придумать, может я где-то что то не так делал

2020-06-08 09:14 UTC, VladislawL commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +    private BigDecimal calculateSubTotalPrice() {
Стоп, так у меня этого уже нет. Я вынес подсчёт прайса в калькулятор

2020-06-08 09:17 UTC, VladislawL commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +            subTotalPrice = subTotalPrice.add(phone.getPrice().multiply(BigDecimal.valueOf(cartItem.getQuantity())));
И тут пофиксано,

2020-06-09 11:39 UTC, AndreikaInactive requested changes

2020-06-09 11:39 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/CartItemValidationException.java
> +        StringBuilder message = new StringBuilder(validationErrors.get(0).getDefaultMessage());
можно и так, но лично я предпочитаю просто отдать errors в эксепшен, а форматировать уже специальным классом где понятно какой формат нужен, допустим в json из хэндлера

2020-06-09 11:39 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/MiniCart.java
> +        miniCart = new HashMap<>();
а почему просто пропертями не засетать в бин?

2020-06-09 11:39 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/config/PropertySourceConfigurer.java
> +        MutablePropertySources envPropSources = ((ConfigurableEnvironment) environment).getPropertySources();
а зачем это нужно? коробки должно хватать

2020-06-09 11:39 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/dao/JdbcPhoneDao.java
> +        Map<String, Object> result = new HashMap<>();
не совсем понял - зачем нужно это отдельно парсить? можешь привести пример?
мб просто передавать лист

2020-06-09 11:39 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/services/DefaultPhoneService.java
> +        phonesOnPage = Integer.parseInt(environment.getProperty("phonesOnPage"));
можно инжектить через ${} в хмл или @Value

2020-06-09 11:39 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/validators/QuantityValidator.java
> +public class QuantityValidator {
если для ui - имплементь Validator спринговый

2020-06-09 11:39 UTC, AndreikaInactive commented on core/src/main/resources/config/sortFields.properties
> +brand=brand
можно в обычный пропертис запихнуть, с каким префиксом

2020-06-09 11:39 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/config/WebAppConfig.java
> +    public Map<String, Object> errorMessage() {
прикольно, а зачем это?

2020-06-09 11:39 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
> +            return ResponseEntity.ok(miniCart.getMiniCart());
сразу бин отдавай ) странно читается

2020-06-09 11:39 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/advicer/AjaxExceptionHandler.java
> +    private Map<String, Object> errorMessage;
так а если просто тут маппить exception в какой то простой error формат? типо список бинов - название ошибки и  месседж с пояснением

2020-06-09 11:39 UTC, AndreikaInactive commented on web/src/main/webapp/WEB-INF/applicationContext.xml
> +                <bean class="org.springframework.core.io.support.ResourcePropertySource">
вроде можно в коробочный property xml tag запихнуть доп сорсы, лучше без кастомного бина

2020-06-09 11:39 UTC, AndreikaInactive commented on web/src/main/webapp/WEB-INF/pages/productList.jsp
> +      <th>
сделай модель аттрибут в контроллере и оттуда все филды передавай

2020-06-09 13:13 UTC, VladislawL commented on core/src/main/java/com/es/core/config/PropertySourceConfigurer.java
> +        MutablePropertySources envPropSources = ((ConfigurableEnvironment) environment).getPropertySources();
Да должно было. Но у меня количество телефонов на страничке находится в пропертис файле, который лежит в вебе. И уже через @Value либо Environment не получается получить это проперти. Как я понял <context:property-placeholder> не сетает проперти в Environment и в других модулях их не видно. По этому я решил в вебе засетать проперти которые связаны с вебом в environment.

2020-06-09 13:42 UTC, VladislawL commented on core/src/main/java/com/es/core/config/PropertySourceConfigurer.java
> +        MutablePropertySources envPropSources = ((ConfigurableEnvironment) environment).getPropertySources();
А, ещё сорт филды через environment получать во время выполнения.

2020-06-09 15:08 UTC, VladislawL commented on core/src/main/java/com/es/core/dao/JdbcPhoneDao.java
> +        Map<String, Object> result = new HashMap<>();
Ну вообще я не вижу лучшего способа как это можно сделать. В строке может быть несколько слов, и я хотел чтобы поиск производился по каждому слову. То есть если строка состоит из 3 слов то создастся мапа с ключами word0, word1, word2, дальше я генерирую строку lower(brand) like :word0 or lower(model) like :word0 or и тд только с word1, word2 для sql запросу.

2020-06-09 17:38 UTC, VladislawL commented on core/src/main/java/com/es/core/validators/QuantityValidator.java
> +public class QuantityValidator {
У меня так было до того как открыл пулреквест. Вроде порешали на том что валидность quantity буду проверять перед добавлением

2020-06-10 14:52 UTC, VladislawL commented on web/src/main/java/com/es/phoneshop/web/controller/converter/StringToSortOrder.java
> +            return Enum.valueOf(SortOrder.class, sortOrder);
Да, спринг и сам сможет это сделать. Но если в enum'е не найдётся константа, то будет брошена ошибка и я бы хотел такой случай перехватить и использовать какое-нибудь дефолтное значение

2020-06-11 20:36 UTC, AndreikaInactive requested changes

2020-06-11 20:36 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        cart.setSubTotalPrice(priceCalculatorService.calculateSubtotalPrice(cart));
прайсы на карте могут быть разными, лучше все их сетать в методе прайс сервиса

2020-06-11 20:36 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/MiniCart.java
> +        subTotalPrice = BigDecimal.ZERO.toString();
юзай бд, а на фронте уже форматировать в нужное представление, универсальнее и например формат по локали можно юзать
если стринг, то уже ничего с ним не сделаешь

2020-06-11 20:36 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/dao/JdbcPhoneDao.java
> +    private PropertyService sortFieldPropertyService;
как и брату - квери через лайки и вайлдарды будет проще, проперти сервис не нужен - всё можно инжектить через спринг конвершен
посмотри какие примеры для работы с property placeholder

2020-06-11 20:36 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/services/DefaultPhoneService.java
> +    @Value("#{propertySource['phonesOnPage']}")
просто по ключу инжекть

2020-06-11 20:36 UTC, AndreikaInactive commented on core/src/test/java/com/es/core/services/DefaultPhoneServiceTest.java
> +    @Value("#{propertySource['phonesOnPage']}")
и тут

2020-06-11 20:36 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
> +            miniCart.setSubTotalPrice(priceFormatter.format(cart.getSubTotalPrice(), LocaleContextHolder.getLocale()));
сделай статический метод в миникарте fromCart, будет красивее
форматировать можно и на фронте

2020-06-11 20:36 UTC, AndreikaInactive commented on web/src/main/webapp/WEB-INF/pages/productList.jsp
> +      <th>
м?

2020-06-12 08:26 UTC, VladislawL commented on core/src/main/java/com/es/core/services/DefaultPhoneService.java
> +    @Value("#{propertySource['phonesOnPage']}")
через ${} не хочет работать. Падает с ошибкой Could not resolve placeholder 'phonesOnPage' in value "${phonesOnPage}". У меня же phonesOnPage лежит в вебе. Наверное из-за этого так не работает, у Стаса просто все проперти лежат в application.properties кор модуля и всё окей,. Может так же сделать?

2020-06-12 18:55 UTC, VladislawL commented on core/src/main/java/com/es/core/dao/JdbcPhoneDao.java
> +    private PropertyService sortFieldPropertyService;
Через ? квери как-то наоборот сложнее получается, т.к. там идёт brand like or model like. Поэтому слова нужно будет продублировать. Как мне кажется NamedJdbcTemplate в этом плане удобнее, т.к. параметр я могу переиспользовать. Можно попробовать поменять стратегию поиска, например, делать поиск не по каждому слову а на все searchQuery

2020-06-12 20:54 UTC, VladislawL commented on web/src/main/webapp/WEB-INF/pages/productList.jsp
> +      <th>
Так ну я вроде сделал. Но есть вопросы. Всё ли хорошо с этим циклом, ну в том плане что мы же потом в другом цикле строки для телефонов формируем, и мне кроме как if 'ов в голову ничего не приходит + если в проперти файле атрибуты поменять местами, то уже колонки будут не соответствовать. В общем то будет ли это проблемой в будущем?

2020-06-14 15:05 UTC, AndreikaInactive approved these changes

2020-06-14 15:05 UTC, merged