Task 3 product details and cart pages
VladislawL/phoneshop pull request #3
Opened 2020-06-19 17:14 UTC by VladislawL

2020-06-22 07:44 UTC, AndreikaInactive requested changes

2020-06-22 07:44 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/CartItemValidationException.java
> +        for (int i = 1; i < validationErrors.size(); i++) {
форматируй респонс эксепшена в адвайсе или еррор хелпере

2020-06-22 07:44 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/dao/JdbcPhoneDao.java
> +        if (n > 0) {
попробуй как нибудь через .joining для изначального листа кодов

2020-06-22 07:44 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
> +        cartPageDataValidator.validate(cartPageData, errors);
по валидации и pageData такие же вопросы как и брату
зачем в getCart это мапить? да и вообще, нас по идее интересует только некая updateForm

2020-06-22 07:44 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
> +        response.put("miniCart", miniCart);
то же по миникарте

2020-06-22 07:44 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/ProductDetailsPageController.java
> +        model.addAttribute("phone", phoneService.getPhoneById(id));
а здесь где миникарта?

2020-06-22 07:44 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/filter/GetMethodConvertingFilter.java
> +                return "GET";
и это

2020-06-22 07:57 UTC, VladislawL commented on web/src/main/java/com/es/phoneshop/web/filter/GetMethodConvertingFilter.java
> +                return "GET";
а здесь в том плане как и у стаса?

2020-06-23 10:35 UTC, VladislawL commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
> +        cartPageDataValidator.validate(cartPageData, errors);
не понял в чём проблема с мапингом, вроде бы же всё окей. или проблема в том что всё мапится на /cart? и для апдейта сделать другой маппинг типа /cart/update?

2020-06-23 10:40 UTC, VladislawL commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
> +        response.put("miniCart", miniCart);
Ну где можно я через интерсептор к реквесту добавляю атрибут миникарта. Ну а тут получается ответ будет json.

2020-06-23 13:46 UTC, AndreikaInactive requested changes

2020-06-23 13:46 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/CartItem.java
> +    @PositiveOrZero(message = "{negative.quantity}")
думаю будет проще Min(0)

2020-06-23 13:46 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +                if (cartItem.isPresent()) {
я ж советовал один метод addOrUpdate сделать, для того чтобы такое не писать
многовато if else выходит с опшионалом, обычно стоит подумать над рефакторингом

2020-06-23 13:46 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/dao/JdbcPhoneDao.java
> +    private String generateInConstraint(List<Long> keys) {
https://stackoverflow.com/questions/1327074/how-to-execute-in-sql-queries-with-springs-jdbctemplate-effectivly

2020-06-23 13:46 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/advicer/AjaxExceptionHandler.java
> +        String message = exceptionFormatter.formatExceptionMessageUsingCode(e.getCode(), new Long[]{e.getStock()});
сразу возвращай ajaxError из форматтера, пусть вся логика будет там

2020-06-23 13:46 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
> +        cartPageDataValidator.validate(cartPageData, errors);
ну, я бы хотел видеть разделение - в модель мы закидываем просто cart или в случае необходимости перемапленный карт (но с generic структурой, а не под конкретную страницу, чтобы юзать везде где отображаем карт), а в update пусть приходит уже спец для этой операции форма

2020-06-23 13:46 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/interceptor/CurrencyInterceptor.java
> +        request.setAttribute("currencySymbol", priceFormatter.getDefaultCurrency());
1. в мвц работай с моделью а не реквестом, 2. так ли нужен интерсептор?

2020-06-23 13:46 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/interceptor/MiniCartInterceptor.java
> +        request.setAttribute("miniCart", miniCart);
в модель

2020-06-23 15:00 UTC, VladislawL commented on web/src/main/java/com/es/phoneshop/web/interceptor/CurrencyInterceptor.java
> +        request.setAttribute("currencySymbol", priceFormatter.getDefaultCurrency());
ну у меня много где нужно добавлять символ валюты (все страницы обёрнуты в master тег и в хедере есть раздел для мини карты, где собственно цена и форматируется), так что почему бы и нет, или в том плане что есть что то другое для таких нужд

2020-06-24 14:59 UTC, VladislawL commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
> +        cartPageDataValidator.validate(cartPageData, errors);
С разделением, у меня что-то не пошлой, 1) если использовать какой нибудь класс для апдейта типа CartUpdateFrom, его и в jsp нужно использовать, тк errors свяжется именно с ним и 2) если в getCart не добавлять в модель cartUpdateForm, то будет ошибка на jsp, что не удалось его найти и если его добавлять в getCart то фактически всё осталось как и было. Поэтому я просто всю карту замапил в cartPageData. Но, что касается generic структуры я, если честно, не понял) ты же имел в виду использовать <> (под дженериками я именно это и понимаю), просто если так то я не понял где это может быть.

2020-06-26 13:17 UTC, merged