Task 4 order
VladislawL/phoneshop pull request #4
Opened 2020-07-06 13:35 UTC by VladislawL

2020-07-07 21:32 UTC, AndreikaInactive commented
посмотри пока плз комменты у брата, вроде есть совпадающее

2020-07-14 16:01 UTC, AndreikaInactive requested changes

2020-07-14 16:01 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/dao/JdbcOrderDao.java
> +            ":totalPrice, (select id from orderStatus where status = :status))";
а зачем отдельная таблица? мб проще просто стрингой

2020-07-14 16:01 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/dao/JdbcOrderDao.java
> +        for (int i = 0; i < orderItems.size(); i++) {
можно ж по идее все разом удалить

2020-07-14 16:01 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/dao/JdbcOrderDao.java
> +            stockDao.decreaseProductStock(orderItem.getPhone().getId(), orderItem.getQuantity());
очень странно - сток обычно менеджится на уровне сервиса, как минимум будет сюрприз для тех кто вызовет метод ради сэйва

2020-07-14 16:01 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/dao/JdbcOrderDao.java
> +        for (OrderItem orderItem : orderItems) {
не уровень дао

2020-07-14 16:01 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/dao/JdbcStockDao.java
> +        if (stock >= quantity) {
а сразу ретурн сделать?)

2020-07-14 16:01 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/order/OrderItemRowMapper.java
> +        Phone phone = phoneService.getPhoneById(rs.getLong("phoneId"));
а дао не хватит?

2020-07-14 16:01 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/order/OrderServiceImpl.java
> +            throw new OrderNotFoundException(uuid.toString());
orelsethrow

2020-07-14 16:01 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/order/OrderServiceImpl.java
> +            throw new OrderNotFoundException(id.toString());
то же

2020-07-14 16:01 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/order/OrderServiceImpl.java
> +        priceCalculator.calculateTotalPrice(order);
а зачем пересчитывать? просто карту пересчитать

2020-07-14 16:01 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/order/OrderServiceImpl.java
> +        order.setOrderItems(getOrderItemsFromCart(cart, order));
не совсем понимаю зачем нужно апдейдить - один раз создаем ордер при сабмите

2020-07-14 16:01 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/order/OrderServiceImpl.java
> +        order.setFirstName(orderPageData.getFirstName());
из пейдж даты контакт инфо? странновато
зачем отдельный метод?

2020-07-14 16:01 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/order/OrderServiceImpl.java
> +        orderDao.save(order);
а всякие чеки по стоку? и добавьте хоть логгинг какой

2020-07-14 16:01 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/services/DefaultPriceCalculator.java
> +    public void calculateTotalPrice(Order order) {
думаю ненужно

2020-07-14 16:01 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/services/DefaultPriceCalculator.java
> +        return deliveryPrice;
и это

2020-07-14 16:01 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/validators/OrderItemsValidator.java
> +        List<?> orderItems = (List) o;
странное приведение )

2020-07-14 16:01 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/validators/OrderItemsValidator.java
> +            if (!stockDao.checkStock(orderItem.getPhone().getId(), orderItem.getQuantity())) {
в сток сервисе сделай метод, можно прост возвращ колво стока

2020-07-14 16:01 UTC, AndreikaInactive commented on pom.xml
> +        <groupId>com.googlecode.libphonenumber</groupId>
зачем вы дублируете? только в кор пом же

2020-07-14 16:01 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderOverviewPageController.java
> +        model.addAttribute("attributes", attributeService.getAttributes());
шо то странное так и осталось

2020-07-14 16:01 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +    public String getOrder(@ModelAttribute CartPageData cartPageData, Errors errors, HttpSession httpSession, Model model) {
на гет всё это делать? это как?

2020-07-14 16:01 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +            if (httpSession.getAttribute(ORDER_SESSION_ATTRIBUTE_NAME) == null) {
странные манипуляции - у тебя есть карт компонент, а ордер можно создавать только в момент сабмита из карты

2020-07-14 16:01 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +            cartPageData.setSubTotalPrice(cart.getSubTotalPrice());
не здесь это сетать уже

2020-07-14 16:01 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +            orderService.setContactInformation(order, orderPageData);
тогда уж в один метод это все делать, зачем такое разделение

2020-07-14 18:15 UTC, VladislawL commented on core/src/main/java/com/es/core/dao/JdbcOrderDao.java
> +            ":totalPrice, (select id from orderStatus where status = :status))";
Ну стрингой 100% проще будет, мне вот казалось, что хранить статусы в отдельной таблице выглядит логично, чем-то похоже на то как они в джаве хранятся в enum

2020-07-14 20:33 UTC, VladislawL commented on core/src/main/java/com/es/core/order/OrderServiceImpl.java
> +        orderDao.save(order);
ну чеки по стоку у меня в дао были, я так понял такие проверки стоит выносить на уровень сервиса, так?

2020-07-14 20:56 UTC, VladislawL commented on pom.xml
> +        <groupId>com.googlecode.libphonenumber</groupId>
а всё понял, у меня и скорее всего у стаса все депенденси объявлены в dependencyMenegment, и чтобы дочерние модули их унаследовали нужно продублировать, но без версии, думаю всё окей здесь) конечно можно все общие депенденси вынести из dependencyMenegment в просто dependency

2020-07-14 20:56 UTC, VladislawL commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderOverviewPageController.java
> +        model.addAttribute("attributes", attributeService.getAttributes());
не понял)

2020-07-14 21:03 UTC, VladislawL commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +    public String getOrder(@ModelAttribute CartPageData cartPageData, Errors errors, HttpSession httpSession, Model model) {
Ну у нас же на карте есть 2 кнопки апдейт и ордер, я вот подумал, что было бы удобно, если бы по нажатию ордер также апдейтилась карта, ведь всё таки можно что то поменять и не нажать апдейт и дальше этого не заметить, или всё таки будет лучше если написать без апдейта карты?

2020-07-15 09:43 UTC, VladislawL commented on core/src/main/java/com/es/core/order/OrderServiceImpl.java
> +        order.setFirstName(orderPageData.getFirstName());
ну да) ну типа я задумывал его использовать, как объект, который будет хранить контактную информацию и список ордер айтемов, и по которому также всё это будет валидироваться. Ну то есть я не вижу проблемы, можешь чуть поподробнее?
Метод чуть что я удалю это можно и в контроллере сделать

2020-07-15 13:13 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderOverviewPageController.java
> +        model.addAttribute("attributes", attributeService.getAttributes());
ну, эти аттрибуты - непонятно что это

2020-07-15 13:14 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +    public String getOrder(@ModelAttribute CartPageData cartPageData, Errors errors, HttpSession httpSession, Model model) {
ну как минимуму - будет очень тяжело сделать правильную синхронизацию
да и зачем

2020-07-15 14:46 UTC, VladislawL commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderOverviewPageController.java
> +        model.addAttribute("attributes", attributeService.getAttributes());
а так это же ещё с первой таски или второй, ты там сказал создать атрибуты которые я на джсп буду через цикл хэндлить, ну собственно это имена столбцов и булевское значение которое показывает является ли поле сортируемым или нет.

2020-07-15 20:00 UTC, VladislawL commented on core/src/main/java/com/es/core/services/DefaultPriceCalculator.java
> +    public void calculateTotalPrice(Order order) {
Ну, мне наоборот кажется это удобным ведь там, где мне нужно посчитать тотал прайс и засетать деливери прайс, я делаю 2 повторяющихся действия это заинжектить деливери прайс через Value и сложить его с сабтотал прайсом + деливери прайс не будет всегда так просто считаться) напиши плиз если моя логика неверна)

2020-07-16 14:12 UTC, AndreikaInactive requested changes

2020-07-16 14:12 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/services/DefaultStockService.java
> +        for (Map.Entry<Long, Long> phone : phones.entrySet()) {
лучше метод для одного и вызывать в цикле из другого сервиса

2020-07-16 14:12 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +        model.addAttribute("totalPrice", priceCalculator.calculateTotalPrice(cart));
а зачем считать прайс отдельно? все уже должно быть на карте, а карта будет в модели

2020-07-16 14:12 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> -            model.addAttribute("attributes", attributeService.getAttributes());
getOrder вызови просто

2020-07-16 14:12 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +        Order order = orderService.createOrder(cart);
а зачем сохранять до валидации?

2020-07-16 14:53 UTC, VladislawL commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +        Order order = orderService.createOrder(cart);
а он и не сохраняется) просто создаётся объект по карте. вообще на этом этапе такое нужно чтобы получить ордер айтемы, но я могу конвертить карт айтемы в ордер айтемы сразу в контроллере и вызывать create в if.

2020-07-16 15:18 UTC, VladislawL commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +        model.addAttribute("totalPrice", priceCalculator.calculateTotalPrice(cart));
т.е. и у карты должны быть поля deliveryPrice и totalPrice. Просто не выглядит ли это странно? ну, например, deliveryPrice же определяется при ордере. Или ты имел в виду, что totalPrice здесь в принципе не нужно считать, а просто складывать там где нужно delivery с subTotal. например на джспишке.

2020-07-16 19:45 UTC, VladislawL commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +        Order order = orderService.createOrder(cart);
Хотя нет, для ордер айтемов нужен ордер, но можно просто карт айтемы валидировать и потом уже создавать ордер

2020-07-20 13:24 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +        model.addAttribute("totalPrice", priceCalculator.calculateTotalPrice(cart));
ну почему странно - тебе же нужно показать текущий тотал карты, который получит юзер при сабмите. Может сверху будут еще промоушеные итд. Так что все прайсы - тотал деливери саб - сетай на карту во время репрайса в сервисе

2020-07-20 13:25 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +        Order order = orderService.createOrder(cart);
да, лучше сперва завалидируй форму а потом создавай ордер

2020-07-21 11:36 UTC, AndreikaInactive approved these changes

2020-07-21 11:36 UTC, merged