Task 5 admin page
VladislawL/phoneshop pull request #5
Opened 2020-07-23 07:36 UTC by VladislawL

2020-07-23 08:51 UTC, AndreikaInactive requested changes

2020-07-23 08:51 UTC, AndreikaInactive commented on web/pom.xml
> +    </dependency>
то же что и у брата по пому - зачем дубликаты?

2020-07-23 08:51 UTC, AndreikaInactive commented on web/src/main/webapp/WEB-INF/spring-security.xml
> +        <logout logout-success-url="/login?logout"  />
jsession обычно удаляют

2020-07-23 08:51 UTC, AndreikaInactive commented
посмотри плз комменты у брата, почти все относится

2020-07-28 11:33 UTC, AndreikaInactive requested changes

2020-07-28 11:33 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/admin/OrdersPageController.java
> +        return orderStatus.toString();
то же что и брату по ResponseEntity

2020-07-28 11:33 UTC, AndreikaInactive commented on web/src/main/webapp/resources/js/script.js
> +        url: window.location,
ну, напиши уже путь к контроллеру явно )

2020-07-28 11:33 UTC, AndreikaInactive commented on web/src/test/java/com/es/phoneshop/web/controller/pages/IntegrationTest.java
> +@Target({ElementType.TYPE})
почему аннотация?

2020-07-28 14:23 UTC, VladislawL commented on web/src/test/java/com/es/phoneshop/web/controller/pages/IntegrationTest.java
> +@Target({ElementType.TYPE})
Да я и сам не знаю, просто у стаса в комментариях было что то написано про IntegrationTest аннотацию, ну я помню в коре мы писали абстрактный класс, тут получается так же сделать? А и еще может быть это глупый вопрос, но что не так с таким подходом? Я единственное заметил что RunWith тут не работает

2020-07-28 20:01 UTC, AndreikaInactive commented on web/src/test/java/com/es/phoneshop/web/controller/pages/IntegrationTest.java
> +@Target({ElementType.TYPE})
ну, я то же написал - если и то и то работает, то норм, но мы ж вроде раньше делали абстрактный

2020-07-28 20:01 UTC, AndreikaInactive commented on web/src/test/java/com/es/phoneshop/web/controller/pages/IntegrationTest.java
> +@Target({ElementType.TYPE})
чего бы не реюзнуть

2020-07-28 20:03 UTC, merged

2020-07-28 20:03 UTC, AndreikaInactive commented
а чего коммит брата показывает?)

2020-07-28 20:49 UTC, VladislawL commented
А так я с его ноутбука делал там наверное в гите его аккаунт был